name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx for building the image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 4: Set up Google Cloud SDK for Docker
      - name: Set up Google Cloud SDK
        run: gcloud auth configure-docker gcr.io --quiet

      # Step 5: Build and Push Docker Image to Google Container Registry (GCR)
      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/beauty-store:latest -f Dockerfile .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/beauty-store:latest

      # Step 6: Deploy to Google Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy beauty-store \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/beauty-store:latest \
            --platform managed \
            --allow-unauthenticated \
            --region ${{ secrets.GCP_REGION }} \
            --set-env-vars DATABASE_URL=${{ secrets.MONGODB_URI }},JWT_SECRET=${{ secrets.JWT_SECRET }} \
